import type { Recipe } from './types';

// --- Locally Stored Recipe Images ---
// These are base64-encoded SVGs, ensuring they are part of the app's code, load instantly, and never break.

const JOLLOF_RICE_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCIgeTE9IjAiIHgyPSIxIiB5Mj0iMSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI0Y1OUUwQiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iI0VGNDQ0NCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHdpZHRoPSI2MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRkZGQkVCIi8+PHBhdGggZD0iTTMwMCw1MCBDNDEwLjQ2LDUwIDUwMCwxMzkuNTQgNTAwLDI1MCBDNTAwLDM2MC40NiA0MTAuNDYsNDUwIDMwMCw0NTAgQzE4OS41NCw0NTAgMTAwLDM2MC40NiAxMDAsMjUwIEMxMDAsMTM5LjU0IDE4OS41NCw1MCAzMDAsNTAgWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwgLTUwKSIgZmlsbD0idXJsKCNnKSIvPjx0ZXh0IHg9IjMwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2VyaWYiIGZvbnQtc2l6ZT0iNDgiIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBkb21pbmFudC1iYXNlbGluZT0ibWlkZGxlIiBmb250LXdlaWdodD0iYm9sZCI+Sm9sbG9mIFJpY2U8L3RleHQ+PC9zdmc+';
const BOBOTIE_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCIgeTE9IjAiIHgyPSIxIiB5Mj0iMSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI0ZCQkYyNCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iI0Q5NzcwNiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHdpZHRoPSI2MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRkVGM0M3Ii8+PHJlY3QgeD0iMTAwIiB5PSIxMDAiIHdpZHRoPSI0MDAiIGhlaWdodD0iMjAwIiByeD0iMjAiIGZpbGw9InVybCgjZykiLz48dGV4dCB4PSIzMDAiIHk9IjIwMCIgZm9udC1mYW1pbHk9InNlcmlmIiBmb250LXNpemU9IjQ4IiBmaWxsPSJ3aGl0ZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgZm9udC13ZWlnaHQ9ImJvbGQiPkJvYm90aWU8L3RleHQ+PC9zdmc+';
const WAAKYE_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCIgeTE9IjAiIHgyPSIxIiB5Mj0iMSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzkyNDAwRSIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzc4MzUwRiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHdpZHRoPSI2MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRkVGM0M3Ii8+PGNpcmNsZSBjeD0iMzAwIiBjeT0iMjAwIiByPSIxNjAiIGZpbGw9InVybCgjZykiLz48dGV4dCB4PSIzMDAiIHk9IjIwMCIgZm9udC1mYW1pbHk9InNlcmlmIiBmb250LXNpemU9IjQ4IiBmaWxsPSJ3aGl0ZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgZm9udC13ZWlnaHQ9ImJvbGQiPldhYWt5ZTwvdGV4dD48L3N2Zz4=';
const SUKUMA_WIKI_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCIgeTE9IjAiIHgyPSIxIiB5Mj0iMSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzEwQjk4MSIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzA1OTY2OSIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHdpZHRoPSI2MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRUNGREY1Ii8+PHBhdGggZmlsbD0idXJsKCNnKSIgZD0iTTAgMjAwIFEgMTUwIDEwMCAzMDAgMjAwIFQgNjAwIDIwMCBWIDQwMCBIIEwgMCBaIiAvPjx0ZXh0IHg9IjMwMCIgeT0iMjUwIiBmb250LWZhbWlseT0ic2VyaWYiIGZvbnQtc2l6ZT0iNDgiIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBkb21pbmFudC1iYXNlbGluZT0ibWlkZGxlIiBmb250LXdlaWdodD0iYm9sZCI+U3VrdW1hIFdpa2k8L3RleHQ+PC9zdmc+';
const CHICKEN_TAGINE_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCIgeTE9IjAiIHgyPSIxIiB5Mj0iMSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI0Y1OUUwQiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzc4MzUwRiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHdpZHRoPSI2MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRkZGQUYwIi8+PHBhdGggZD0iTSAzMDAsNTAgTCAxNTAsMzAwIEwgNDUwLDMwMCBaIiBmaWxsPSJ1cmwoI2cpIiAvPjxyZWN0IHg9IjEyMCIgeT0iMzAwIiB3aWR0aD0iMzYwIiBoZWlnaHQ9IjUwIiByeD0iMTAiIGZpbGw9InVybCgjZykiIC8+PHRleHQgeD0iMzAwIiB5PSIyMDAiIGZvbnQtZmFtaWx5PSJzZXJpZiIgZm9udC1zaXplPSI0MCIgZmlsbD0id2hpdGUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtd2VpZ2h0PSJib2xkIj5DaGlja2VuIFRhZ2luZTwvdGV4dD48L3N2Zz4=';

export const FALLBACK_RECIPE_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjYwMCAgaGVpZ2h0PSI0MDAiIGZpbGw9IiNFNUU3RUIiLz48cGF0aCBkPSJNMjI1LDI1MCBDMjI1LDI3Ny42MSAyMDIuNjEsMzAwIDE3NSwzMDQgQzE0Ny4zOSwzMDAgMTI1LDI3Ny42MSAxMjUsMjUwIEMxMjUsMjIyLjM5IDE0Ny4zOSwyMDAgMTc1LDIwMCBDMjAyLjYxLDIwMCAyMjUsMjIyLjM5IDIyNSwyNTAgWiBNNDc1LDEyNSBMNTI1LDE3NSBMNDI1LDE3NSBaIE0zMDAsMTAwIEwzNTAsMjAwIEwyNTAsMjAwIFoiIGZpbGw9IiM5Q0EzQUYiLz48dGV4dCB4PSIzMDAiIHk9IjM1MCIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMjQiIGZpbGw9IiM0QjU1NjMiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkltYWdlIE5vdCBBdmFpbGFibGU8L3RleHQ+PC9zdmc+';

export const CURATED_RECIPES: Recipe[] = [
  {
    id: 'nigerian-jollof-rice',
    name: 'Nigerian Jollof Rice',
    description: 'A legendary one-pot dish that\'s a staple at every Nigerian party. It\'s a smoky, spicy, and savory rice dish that will have you coming back for more.',
    imageUrl: JOLLOF_RICE_IMAGE,
    prepTime: '20 mins',
    cookTime: '50 mins',
    servings: '6',
    difficulty: 'Medium',
    isCurated: true,
    category: 'Nigerian',
    source: 'KOBIRI',
    ingredients: [
      { name: 'Long grain parboiled rice', amount: '4 cups' },
      { name: 'Tomato puree', amount: '400g' },
      { name: 'Red bell peppers (Tatashe)', amount: '4' },
      { name: 'Scotch bonnet peppers (Ata Rodo)', amount: '2-3' },
      { name: 'Onions', amount: '2 large' },
      { name: 'Vegetable oil', amount: '1/2 cup' },
      { name: 'Chicken or beef stock', amount: '5 cups' },
      { name: 'Thyme', amount: '1 tsp' },
      { name: 'Curry powder', amount: '1 tsp' },
      { name: 'Bay leaves', amount: '2' },
      { name: 'Salt and seasoning cubes', amount: 'to taste' },
    ],
    instructions: [
      { step: 1, description: 'Blend the bell peppers, scotch bonnets, and one onion until smooth to create the pepper base.' },
      { step: 2, description: 'In a large pot, heat vegetable oil and sauté the remaining chopped onion until fragrant.' },
      { step: 3, description: 'Stir in the tomato puree and fry for 10-15 minutes, stirring continuously to prevent burning. This step is crucial for the smoky flavor.' },
      { step: 4, description: 'Pour in the blended pepper base and cook for another 10 minutes. Add thyme, curry powder, bay leaves, salt, and seasoning cubes.' },
      { step: 5, description: 'Wash the rice thoroughly and add it to the pot. Stir well to coat the rice with the sauce.' },
      { step: 6, description: 'Pour in the stock, just enough to cover the rice. Cover the pot with a tight-fitting lid (and foil for a better seal) and cook on low heat for 30-40 minutes until the rice is tender.' },
      { step: 7, description: 'Once cooked, fluff the rice with a fork and serve hot with your favorite protein.' },
    ],
  },
  {
    id: 'south-african-bobotie',
    name: 'South African Bobotie',
    description: 'A beloved South African casserole, Bobotie features spiced minced meat baked with a creamy, golden egg-based topping. A perfect blend of sweet and savory.',
    imageUrl: BOBOTIE_IMAGE,
    prepTime: '25 mins',
    cookTime: '45 mins',
    servings: '4-6',
    difficulty: 'Medium',
    isCurated: true,
    category: 'South African',
    source: 'KOBIRI',
    ingredients: [
      { name: 'Brown bread, crusts removed', amount: '1 slice' },
      { name: 'Milk', amount: '1 cup' },
      { name: 'Lean ground beef', amount: '1 kg' },
      { name: 'Onion, chopped', amount: '1 large' },
      { name: 'Butter', amount: '2 tbsp' },
      { name: 'Curry powder (medium)', amount: '2 tbsp' },
      { name: 'Turmeric', amount: '1 tsp' },
      { name: 'Apricot jam', amount: '3 tbsp' },
      { name: 'Brown vinegar', amount: '2 tbsp' },
      { name: 'Raisins or sultanas', amount: '1/2 cup' },
      { name: 'Flaked almonds', amount: '1/4 cup' },
      { name: 'Bay leaves', amount: '3-4' },
      { name: 'Eggs', amount: '2 large' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      { step: 1, description: 'Preheat oven to 180°C (350°F). Soak the bread in half of the milk.' },
      { step: 2, description: 'In a pan, melt butter and sauté the onion until soft. Add the ground beef and cook until browned.' },
      { step: 3, description: 'Squeeze the milk from the bread (reserving the milk) and crumble the bread into the meat mixture.' },
      { step: 4, description: 'Add curry powder, turmeric, apricot jam, vinegar, raisins, and half the almonds. Season with salt and pepper. Mix well.' },
      { step: 5, description: 'Spoon the mixture into a greased ovenproof dish and press down. Insert bay leaves vertically into the meat.' },
      { step: 6, description: 'Beat the eggs with the remaining milk and the reserved milk from the bread. Pour this custard mixture over the meat.' },
      { step: 7, description: 'Sprinkle with the remaining almonds and bake for 35-45 minutes, or until the topping is set and golden brown.' },
      { step: 8, description: 'Let it stand for 10 minutes before serving with yellow rice and chutney.' },
    ],
  },
  {
    id: 'ghanaian-waakye',
    name: 'Ghanaian Waakye',
    description: 'A beloved Ghanaian street food classic, Waakye is a hearty and flavorful dish of rice and beans cooked with dried sorghum leaves, giving it a distinctive color.',
    imageUrl: WAAKYE_IMAGE,
    prepTime: '15 mins',
    cookTime: '1 hr',
    servings: '4',
    difficulty: 'Medium',
    isCurated: true,
    category: 'Ghanaian',
    source: 'KOBIRI',
    ingredients: [
      { name: 'Long grain rice', amount: '2 cups' },
      { name: 'Black-eyed peas or red beans', amount: '1 cup' },
      { name: 'Waakye leaves (or 1/2 tsp baking soda)', amount: 'a handful' },
      { name: 'Water', amount: '4-5 cups' },
      { name: 'Salt', amount: 'to taste' },
    ],
    instructions: [
      { step: 1, description: 'Soak the beans overnight or for at least 4 hours. Drain and rinse.' },
      { step: 2, description: 'In a large pot, add the beans, waakye leaves (or baking soda), and enough water to cover. Bring to a boil and cook for about 30 minutes until the beans are partially tender.' },
      { step: 3, description: 'Wash the rice thoroughly and add it to the pot with the beans. Add salt and stir. Ensure the water is about an inch above the rice level, adding more if necessary.' },
      { step: 4, description: 'Cover the pot and cook on low-medium heat until the rice is cooked and the water is absorbed, about 20-25 minutes.' },
      { step: 5, description: 'Remove the waakye leaves. Fluff the rice and beans mixture with a fork.' },
      { step: 6, description: 'Serve hot with your favorite accompaniments like shito (hot sauce), stew, gari, or fried plantains.' },
    ],
  },
  {
    id: 'kenyan-sukuma-wiki',
    name: 'Kenyan Sukuma Wiki',
    description: 'Literally "to push the week," Sukuma Wiki is a nutritious and affordable Kenyan staple made from collard greens sautéed with onions and tomatoes.',
    imageUrl: SUKUMA_WIKI_IMAGE,
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '4',
    difficulty: 'Easy',
    isCurated: true,
    category: 'Kenyan',
    source: 'KOBIRI',
    ingredients: [
      { name: 'Collard greens (Sukuma)', amount: '1 large bunch' },
      { name: 'Large onion, chopped', amount: '1' },
      { name: 'Tomatoes, diced', amount: '2' },
      { name: 'Vegetable oil', amount: '2 tbsp' },
      { name: 'Salt', amount: 'to taste' },
      { name: 'Beef or vegetable stock cube (optional)', amount: '1/2' },
    ],
    instructions: [
      { step: 1, description: 'Wash the collard greens thoroughly. Remove the tough stems and shred the leaves into thin strips.' },
      { step: 2, description: 'Heat the oil in a large pan or skillet over medium heat. Add the chopped onion and cook until softened, about 3-4 minutes.' },
      { step: 3, description: 'Add the diced tomatoes and cook until they break down into a sauce-like consistency.' },
      { step: 4, description: 'Add the shredded collard greens to the pan. Stir well to combine with the onion and tomato mixture.' },
      { step: 5, description: 'Season with salt and the crumbled stock cube (if using). Stir and cook for 5-10 minutes, or until the greens are tender but still vibrant green.' },
      { step: 6, description: 'Serve immediately as a side dish, traditionally with Ugali.' },
    ],
  },
  {
    id: 'moroccan-chicken-tagine',
    name: 'Moroccan Chicken Tagine',
    description: 'A classic North African stew featuring tender chicken slow-cooked with preserved lemons, olives, and a blend of aromatic spices. A truly iconic Moroccan dish.',
    imageUrl: CHICKEN_TAGINE_IMAGE,
    prepTime: '20 mins',
    cookTime: '1 hr 15 mins',
    servings: '4',
    difficulty: 'Medium',
    isCurated: true,
    category: 'Moroccan',
    source: 'KOBIRI',
    ingredients: [
      { name: 'Chicken pieces (thighs or legs)', amount: '1 kg' },
      { name: 'Onion, finely chopped', amount: '1 large' },
      { name: 'Garlic cloves, minced', amount: '3' },
      { name: 'Fresh ginger, grated', amount: '1 inch' },
      { name: 'Ground cumin', amount: '1 tsp' },
      { name: 'Ground turmeric', amount: '1 tsp' },
      { name: 'Ground cinnamon', amount: '1/2 tsp' },
      { name: 'Preserved lemon, rinsed and quartered', amount: '1' },
      { name: 'Green olives, pitted', amount: '1 cup' },
      { name: 'Chicken stock', amount: '1.5 cups' },
      { name: 'Fresh cilantro and parsley, chopped', amount: '1/4 cup' },
      { name: 'Olive oil', amount: '2 tbsp' },
    ],
    instructions: [
      { step: 1, description: 'In a tagine or large pot, heat olive oil over medium-high heat. Brown the chicken pieces on all sides and set aside.' },
      { step: 2, description: 'In the same pot, add the chopped onion and cook until soft. Add garlic and ginger and cook for another minute until fragrant.' },
      { step: 3, description: 'Stir in the cumin, turmeric, and cinnamon. Return the chicken to the pot.' },
      { step: 4, description: 'Add the chicken stock, preserved lemon quarters, and half of the fresh herbs. Bring to a simmer.' },
      { step: 5, description: 'Cover the pot, reduce the heat to low, and let it simmer for about 1 hour, or until the chicken is tender and cooked through.' },
      { step: 6, description: 'Add the green olives and the remaining herbs. Cook for another 5-10 minutes.' },
      { step: 7, description: 'Serve hot with couscous or crusty bread to soak up the delicious sauce.' },
    ],
  }
];
